version: "3"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 100

  subquery-node:
    image: onfinality/subql-node-ethereum:latest
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      # - -f=ipfs://QmcZssh6m72BGr1hdxeWib9Un4Ss7bL1hyTjzqnQyMPE4F
      - -f=./app
      - --db-schema=lottery-acala
      - --workers=10
      - --batch-size=1
      - --unfinalized-blocks=false
      - --disable-historical
      - --store-flush-interval=3
      # - --network-endpoint=http://host.docker.internal:8545
      - --network-endpoint=https://eth-rpc-acala.aca-api.network
      # - --log-level=debug
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=lottery
      - --playground
      - --indexer=http://subquery-node:3000
